config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from config import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('project.api.urls')),
    url(r'^apicc/', include('project.apicc.urls')),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    # FLAG NvE: temp fix: foregoing error about stack order!
#    url(r'^accounts/login', views.LoginCaptcha.as_view(), name='login_captcha'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

project/apicc/urls.py
# Imports
from django.conf.urls import url, include
from rest_framework import routers
from project.apicc import views


#router = routers.DefaultRouter()
#router.register(r'users', views.UserViewSet)

app_name = 'apicc'
urlpatterns = [
#    url(r'^', include(router.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^updateDB/$', views.save_cryptoasset, name='updateDB'),
    url(r'^momentum_plot/(?P<pname>\d+)/$', views.momentum_plot, name='momentum_plot'),
    url(r'^draw_mpl/$', views.draw_mpl, name='draw_mpl'),
    url(r'^momentum_plot_model/(?P<pname>\d+)/$', views.momentum_plot, name='momentum_plot_model'),
    url(r'^draw_mpl_model/$', views.draw_mpl_model, name='draw_mpl_model'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% block title %}<title>Django DevServer</title>{% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block twitter_card %}{% endblock %}
    <!--Javescript -->
    <!--src: http://www.javascriptkit.com/javatutors/copytoclipboard.shtml-->
    <script type="text/javascript" src="http://www.javascriptkit.com/jkincludes/syntaxhighlight/syntax3/scripts/shCore.js"></script>
    <script type="text/javascript" src="http://www.javascriptkit.com/jkincludes/syntaxhighlight/syntax3/scripts/shBrushJScript.js"></script>
    <!-- Adds w3school standard styling -->
    <!-- remove later -->
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Adds bootstrap3 -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="http://code.jquery.com/jquery-1.11.3.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>

<style>
    <!-- additional style should be migrated to static.css-->
    html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
    .excerpt { margin: 2em}
</style>
<body>

<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-theme w3-top w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
    <a href="{% url 'index' %}" class="w3-bar-item w3-button w3-theme-l1">Home</a>
    <!--<a href="{% url 'apicc:index' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">DCAI</a>-->
  </div>
</div>

<!-- Sidebar -->
{% block sidebar %}
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" style="z-index:3;width:250px;margin-top:43px;" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <a class="w3-bar-item w3-button w3-hover-black" href="{% url 'apicc:draw_mpl_model' %}">Momentum Chart</a>
  <br />
  {% if user.is_authenticated %}
  <a class="w3-bar-item w3-button w3-hover-black" href="">User: {{ user.get_username }}</li>
  <a class="w3-bar-item w3-button w3-hover-black" href="{% url 'apicc:draw_mpl' %}?portfolio=0">Momentum Chart</a>
  <a class="w3-bar-item w3-button w3-hover-black" href="{% url 'apicc:updateDB' %}">Copy CC Top 500</a>
  <!--<a class="w3-bar-item w3-button w3-hover-black" href="#">Link</a>-->
  <a class="w3-bar-item w3-button w3-hover-black" href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
  {% else %}
  <a class="w3-bar-item w3-button w3-hover-black" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}
</nav>
{% endblock %}
<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- Main content: shift it to the right by 250 pixels when the sidebar is visible -->
<div class="w3-main" style="margin-left:250px">

  <div class="w3-row w3-padding-64">
    <!--<div class="w3-twothird w3-container">-->
    <div class="w3-container">
		{% block content %}{% endblock %}
    </div>
    <!--<div class="w3-third small w3-container">
      {% block sidebar_main %}{% endblock%}
    </div>-->
  </div>

<!--  <div class="w3-row">
    <div class="w3-twothird w3-container">
      <h1 class="w3-text-teal">Heading</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum
        dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
    <div class="w3-third w3-container">
      <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p>
    </div>
  </div>

  <div class="w3-row w3-padding-64">
    <div class="w3-twothird w3-container">
      <h1 class="w3-text-teal">Heading</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum
        dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
    <div class="w3-third w3-container">
      <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
      <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p>
    </div>
  </div> -->

  <!-- Pagination -->
  <div class="w3-center w3-padding-32">
    <!-- <div class="w3-bar">
      <a class="w3-button w3-black" href="#">1</a>
      <a class="w3-button w3-hover-black" href="#">2</a>
      <a class="w3-button w3-hover-black" href="#">3</a>
      <a class="w3-button w3-hover-black" href="#">4</a>
      <a class="w3-button w3-hover-black" href="#">5</a>
      <a class="w3-button w3-hover-black" href="#">»</a>
    </div> -->
  </div>

  <footer id="myFooter">
    <div class="w3-container w3-theme-l2 w3-padding-32">
      <h4>Tips go to my Bitcoin PhD fund: 1EgBw1Xvq3R3ksJu6Z49fX2829FqXc8dFw</h4>
    </div>

    <div class="w3-container w3-theme-l1">
      <p>By <a href="https://twitter.com/NCvanEgmond" target="_blank">@NCvanEgmond</a></p>
    </div>
  </footer>

<!-- END MAIN -->
</div>

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
    if (mySidebar.style.display === 'block') {
        mySidebar.style.display = 'none';
        overlayBg.style.display = "none";
    } else {
        mySidebar.style.display = 'block';
        overlayBg.style.display = "block";
    }
}

// Close the sidebar with the close button
function w3_close() {
    mySidebar.style.display = "none";
    overlayBg.style.display = "none";
}
</script>

</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>More stuff to come</h1>

<p>The plan is to make this place a home for the charts I publish on Twitter. 
It's a work in progress. If you feel it's too slow or if you have specific 
things you want to see: Let me know!</p>

<ol>
    <li>[ ] Dynamic chart generation for different portfolios</li>
    <li>[ ] Caching data</li>   
    <li>[ ] Migrate charts from matplotlib to plotly: Making them more informative</li>
    <li>[ ] Fix an SSL certificate</li>
</ol>

{% endblock %}